package model

type PatientResponse struct {
	MedicalRecord  string `db:"medical_record" json:"medical_record"`
	Name           string `db:"name" json:"name"`
	BirthPlace     string `db:"birth_place" json:"birth_place"`
	BirthDate      string `db:"birth_date" json:"birth_date"`
	Gender         string `db:"gender" json:"gender"`
	Blood          string `db:"blood" json:"blood"`
	Education      string `db:"education" json:"education"`
	Religion       string `db:"religion" json:"religion"`
	Wedding        string `db:"wedding" json:"wedding"`
	Nation         string `db:"nation" json:"nation"`
	Language       string `db:"language" json:"language"`
	Disability     string `db:"disability" json:"disability"`
	BPJS           string `db:"bpjs" json:"bpjs"`
	Email          string `db:"email" json:"email"`
	Phone          string `db:"phone" json:"phone"`
	Work           string `db:"work" json:"work"`
	Instance       string `db:"instance" json:"instance"`
	Address        string `db:"address" json:"address"`
	Village        int    `db:"village" json:"village"`
	District       int    `db:"district" json:"district"`
	Regency        int    `db:"regency" json:"regency"`
	Province       int    `db:"province" json:"province"`
	ParentName     string `db:"parent_name" json:"parent_name"`
	ParentWork     string `db:"parent_work" json:"parent_work"`
	ParentAddress  string `db:"parent_address" json:"parent_address"`
	ParentVillage  int    `db:"parent_village" json:"parent_village"`
	ParentDistrict int    `db:"parent_district" json:"parent_district"`
	ParentRegency  int    `db:"parent_regency" json:"parent_regency"`
	ParentProvince int    `db:"parent_province" json:"parent_province"`
}

type PatientRequest struct {
	MedicalRecord  string `db:"medical_record" json:"medical_record"`
	Name           string `db:"name" json:"name"`
	BirthPlace     string `db:"birth_place" json:"birth_place"`
	BirthDate      string `db:"birth_date" json:"birth_date"`
	Gender         string `db:"gender" json:"gender"`
	Blood          string `db:"blood" json:"blood"`
	Education      string `db:"education" json:"education"`
	Religion       string `db:"religion" json:"religion"`
	Wedding        string `db:"wedding" json:"wedding"`
	Nation         string `db:"nation" json:"nation"`
	Language       string `db:"language" json:"language"`
	Disability     string `db:"disability" json:"disability"`
	BPJS           string `db:"bpjs" json:"bpjs"`
	Email          string `db:"email" json:"email"`
	Phone          string `db:"phone" json:"phone"`
	Work           string `db:"work" json:"work"`
	Instance       string `db:"instance" json:"instance"`
	Address        string `db:"address" json:"address"`
	Village        int    `db:"village" json:"village"`
	District       int    `db:"district" json:"district"`
	Regency        int    `db:"regency" json:"regency"`
	Province       int    `db:"province" json:"province"`
	ParentName     string `db:"parent_name" json:"parent_name"`
	ParentWork     string `db:"parent_work" json:"parent_work"`
	ParentAddress  string `db:"parent_address" json:"parent_address"`
	ParentVillage  int    `db:"parent_village" json:"parent_village"`
	ParentDistrict int    `db:"parent_district" json:"parent_district"`
	ParentRegency  int    `db:"parent_regency" json:"parent_regency"`
	ParentProvince int    `db:"parent_province" json:"parent_province"`
}
